// Generates src/themes.css and src/lib/themes.ts from tweakcn theme presets.
// Run on a machine with network access:  node scripts/build-themes.mjs
import { writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// Theme slug (tweakcn registry) -> label shown in Settings.
const THEME_LIST = [
  ["default", "Default"],
  ["claymorphism", "Claymorphism"],
  ["starry-night", "Starry Night"],
  ["twitter", "Twitter"],
  ["perpetuity", "Perpetuity"],
  ["amber-minimal", "Amber Minimal"],
  ["clean-slate", "Clean Slate"],
  ["cosmic-night", "Cosmic Night"],
  ["elegant-luxury", "Elegant Luxury"],
  ["mocha-mousse", "Mocha Mousse"],
  ["kodama-grove", "Kodama Grove"],
  ["nature", "Nature"],
  ["notebook", "Notebook"],
  ["ocean-breeze", "Ocean Breeze"],
  ["sage-garden", "Sage Garden"],
  ["vercel", "Vercel"],
];

const url = (slug) => `https://tweakcn.com/r/themes/${slug}.json`;

function block(selector, vars) {
  const body = Object.entries(vars)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n");
  return `${selector} {\n${body}\n}`;
}

async function main() {
  const cssParts = [
    "/* AUTO-GENERATED by scripts/build-themes.mjs — do not edit by hand. */",
    "/* Themes from https://tweakcn.com — applied via <html data-theme>. */",
    "",
  ];
  const registry = [];

  for (const [slug, label] of THEME_LIST) {
    process.stdout.write(`Fetching ${slug}... `);
    let json;
    try {
      const res = await fetch(url(slug));
      if (!res.ok) throw new Error(`HTTP ${res.status}`);
      json = await res.json();
    } catch (e) {
      console.log(`SKIPPED (${e.message})`);
      continue;
    }

    const theme = json.cssVars?.theme ?? {};
    const light = json.cssVars?.light ?? {};
    const dark = json.cssVars?.dark ?? {};

    cssParts.push(
      `/* ---------- ${label} ---------- */`,
      block(`[data-theme="${slug}"]`, { ...theme, ...light }),
      block(`[data-theme="${slug}"].dark`, { ...theme, ...dark }),
      "",
    );

    registry.push({
      name: slug,
      label,
      swatch: light.primary ?? "oklch(0.205 0 0)",
    });
    console.log("ok");
  }

  await writeFile(resolve(ROOT, "src/themes.css"), cssParts.join("\n") + "\n");

  const names = registry.map((r) => `"${r.name}"`).join(" | ");
  const items = registry
    .map(
      (r) =>
        `  { name: "${r.name}", label: ${JSON.stringify(r.label)}, swatch: "${r.swatch}" },`,
    )
    .join("\n");
  const ts = `// AUTO-GENERATED by scripts/build-themes.mjs — do not edit by hand.
export type Mode = "light" | "dark" | "system";

export type ThemeName = ${names || '"default"'};

export const THEMES: { name: ThemeName; label: string; swatch: string }[] = [
${items}
];
`;
  await writeFile(resolve(ROOT, "src/lib/themes.ts"), ts);

  console.log(`\nGenerated ${registry.length} themes.`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
